version: '3.1'

services:

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - ~/Postgres/BusinessMyLife:/var/lib/postgresql/data
    ports:
      - 5432:5432

  redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
